### ISSUE TITLE
How i can write this key to class?

### ISSUE THREAD

**Issue by SOUx4cx4fx56x69** [PurpleI2P/i2pd-tools#13]
https://github.com/SOUx4cx4fx56x69/i2pd-tools/blob/master/keygen.cpp#L99

**Comment by majestrate** [comment]
what are you trying to do?

**Comment by SOUx4cx4fx56x69** [comment]
@majestrate i try to generate address with tempalate from string

**Comment by majestrate** [comment]
A vanity address generator?

**Comment by SOUx4cx4fx56x69** [comment]
@majestrate yeah.
I change padding in hope that i get that i want, when i get i don't know as that write to keys object.

**Comment by majestrate** [comment]
you need to regenerate keys not just mutate the public key, suggestion:
don't regenerate the eglamal key only generate it once and regenerate the
signing key as fast as possible.

**Comment by orignal** [comment]
@majestrate why do he need to regenerate signing key if there are 96 bytes padding?

**Comment by SOUx4cx4fx56x69** [comment]
*confused*

**Comment by majestrate** [comment]
Ah you're right, nevermind then.

**Comment by SOUx4cx4fx56x69** [comment]
well as i can write `KeyBuf` in class?

**Comment by majestrate** [comment]
why not use a bare pointer to the padding and modify that in place?

**Comment by SOUx4cx4fx56x69** [comment]
hm

**Comment by SOUx4cx4fx56x69** [comment]
I can get this in lib2ipd?

**Comment by orignal** [comment]
@SOUx4cx4fx56x69 check how bitcoin miner does it. It precalculates midstate and recalculate last block with nonce only

**Comment by SOUx4cx4fx56x69** [comment]
@orignal It gooooood, but i don't know as write result to keys:(
