### ISSUE TITLE
Generate authentication string without sub-domain

### ISSUE THREAD

**Issue by Zero3K** [PurpleI2P/i2pd-tools#62]
How do I do that?

**Comment by orignal** [comment]
Usage: regaddr filename address

**Comment by Zero3K** [comment]
Thanks. By the way, please make windows builds of them so I and others can use them without having to manually build them.

**Comment by r4sas** [comment]
https://github.com/PurpleI2P/i2pd-tools/releases/tag/19eb76e-windows
