### ISSUE TITLE
Doesn't compile against i2pd 2.39

### ISSUE THREAD

**Issue by foobaz** [PurpleI2P/i2pd-tools#75]
Compiles and works perfectly with i2pd 2.38, but against 2.39 it fails with a linker error - undefined internationalization symbols in libi2pd.

**Comment by orignal** [comment]
How do you compile?

**Comment by foobaz** [comment]
I'm using the Arch Linux AUR package from https://aur.archlinux.org/packages/i2pd-tools-git/

I've looked more into the issue and it is a problem with the patches in the AUR package, not in i2pd-tools itself. I'm sorry to file the bug in the wrong place.
