### ISSUE TITLE
vain successful - keyinfo "bad key file format"

### ISSUE THREAD

**Issue by seth586** [PurpleI2P/i2pd-tools#76]
Compiled and running on FreeBSD 12.2

I'm looking for a 7 character vanity address, which usually takes a few hours on my E5-2643v3 processor. But when it finds one and exits, I run `keyinfo` on the output I get the following error:

```
./keyinfo keyfile5.dat
bad key file format
```

I also tried on a windows laptop with the release executable (Ryzen 9 5900HX) , and same thing, 6 character vanity addresses work just fine, but whenever I search for and find a 7 character vanity address I get the same error.

**Comment by seth586** [comment]
Looks like the problem persists based on length of time. I had a 6 character vanity address take ~30 minutes, and it also resulted in a bad key.

**Comment by marek22k** [comment]
I've tried the whole thing and I didn't get any errors.

**Comment by Joshix-1** [comment]
had the same issue
ryzen 5 2400g, took few hours
```
~/i2pd-tools|master ⇒  ./vain 'asozial.*' -t 7 -r
Initializing vanity generator (7 threads)

Starting attempt #1:
[+] thread 6 bound
[+] thread 5 bound
[+] thread 4 bound
[+] thread 3 bound
[+] thread 2 bound
[+] thread 1 bound
[+] thread 0 bound
Starting attempt #2:
[+] thread 6 bound
[+] thread 5 bound
[+] thread 4 bound
[+] thread 3 bound
[+] thread 2 bound
[+] thread 1 bound
[+] thread 0 bound
Starting attempt #3:
[+] thread 6 bound
[+] thread 5 bound
[+] thread 4 bound
[+] thread 3 bound
[+] thread 2 bound
[+] thread 1 bound
[+] thread 0 bound

Found address: asozialwsghpuoj33oezjy44ma4e2i7alkgblz5eh6arev3d3ega
Hashes calculated: 18389385845
~/i2pd-tools|master ⇒  ./keyinfo private.dat 
bad key file format
```

**Comment by orignal** [comment]
You must create a file with valid address first and then run vain

**Comment by Mabbs** [comment]
same error with 7 character

**Comment by wipedlifepotato** [comment]
Anyone can to upload a file that was generated? With "bad keys format"...

**Comment by wipedlifepotato** [comment]
So, I will to test it. Will be fixed, if trouble was in create first a dump file. But I have to check.
```
$ ./vain auwuowo -m
Start vanity generator in 4 threads
Thread 3 binded
Thread Thread 2 binded
1 binded
Thread 0 binded```

**Comment by wipedlifepotato** [comment]
444 line, RAND_bytes would(can) be changed to generate a new keys pair and create a dump file is not need. This is will fix the problem

**Comment by wipedlifepotato** [comment]
Another way not kill key and correctly write bytes. Yet, Will be fixed on weekends

**Comment by wipedlifepotato** [comment]
https://github.com/PurpleI2P/i2pd-tools/pull/91
Maybe is will fix this bug.
```
./vain asozial -m
Start vanity generator in 4 threads
Thread 3 binded
Thread 2 binded
Thread 1 binded
Thread 0 binded```

**Comment by wipedlifepotato** [comment]
Was fixed

**Comment by wipedlifepotato** [comment]
antebeot.world/private0.dat
But for now a another bug with increment foundKeys++ line. But is not critical
And another key antebeot.world/private2.dat

**Comment by wipedlifepotato** [comment]
![IMG_20230805_114413_483](https://github.com/PurpleI2P/i2pd-tools/assets/60944239/b9f19622-45c4-497a-a832-e2d311bc9b90)

**Comment by Mabbs** [comment]
> Was fixed

Please make a Windows release while it works well. Thanks.

**Comment by wipedlifepotato** [comment]
Fixed https://github.com/PurpleI2P/i2pd-tools/pull/91

**Comment by wipedlifepotato** [comment]
> > Was fixed
> 
> Please make a Windows release while it works well. Thanks.

https://i2pd.readthedocs.io/en/latest/devs/building/windows/
You can use simillar doings for compile i2pd-tools
But I do.
```
export ARCH='i686'     # or 'x86_64'
export MINGW='mingw32' # or 'mingw64'
pacman -S mingw-w64-$ARCH-boost mingw-w64-$ARCH-openssl mingw-w64-$ARCH-gcc git make
mkdir -p /c/dev/i2pd-tools
cd /c/dev/i2pd-tools
git clone https://github.com/PurpleI2P/i2pd-tools --recursive
cd i2pd-tools
# we need compiler on PATH which is usually heavily cluttered on Windows
export PATH=/$MINGW/bin:/usr/bin
make
```

**Comment by wipedlifepotato** [comment]
compiler drags garbage and exe can be more more more more more less. But...
[Vain.zip](https://github.com/PurpleI2P/i2pd-tools/files/12266948/Vain.zip)
