### ISSUE TITLE
"bad key file format"

### ISSUE THREAD

**Issue by pizFunk** [PurpleI2P/i2pd-tools#83]
hello. i ran i2pd-vain for a few hours with only a pattern argument and on the 9th attempt i got the result:

Found address: ***********
Hashes calculated: 187548083168

however, when running i2pd-keyinfo against the newly generated private.dat file, i get the message "bad key file format."

any idea what went wrong? i'm running it again now on the off-chance i get a usable result

**Comment by orignal** [comment]
You must create .dat file with EdDSA signature first and then run vain

**Comment by pizFunk** [comment]
thanks for your reply, i'll try that now. is that documented somewhere that i missed?

**Comment by pizFunk** [comment]
i've confirmed that creating a dat file before running vain is not required. i was ultimately trying to create a key using a pattern 7 chacters long. i've confirmed that i can create keys by shortening my pattern to a length of 1-6 characters. however, adding the 7th and final character of my pattern continues to fail (and takes a much longer amount of time to do so, unfortunately). any further help would be appreciated.

**Comment by kevcrumb** [comment]
Can confirm this happens with shorter strings too.

As a workaround you may loop `vain` and `keyinfo` until a working result is found.

If this increases the amount of hashes required depends on the actual source of the bug. Maybe it generates a false positive in the first place. Maybe it generates a correct match but then writes it incorrectly to file.

**Comment by wipedlifepotato** [comment]
https://github.com/PurpleI2P/i2pd-tools/issues/76

**Comment by wipedlifepotato** [comment]
Double of issue, can be closed and use for talks about the problem #76 issue.

**Comment by wipedlifepotato** [comment]
Fixed https://github.com/PurpleI2P/i2pd-tools/pull/91
