### ISSUE TITLE
Not using standard library headers

### ISSUE THREAD

**Issue by BruhRain** [PurpleI2P/i2pd-tools#98]
In your file `vain.cpp` you seem to not use the format library.
Well firstly, this is because you're compiling for C++17. <format> is for C++20.

Secondly, why are you using boost, when in C++17, boosts filesystem library was implemented into the standard library.
So was chrono, and date-time. the only acceptable boost library would be the program-options library.

It seems stupid to use third-party libraries when they're already implemented into the standard library, AND then also not using your brain to figure out that <format> is C++20. if you had one look at [cppreference std::format](https://en.cppreference.com/w/cpp/header/format) you would realise that it says "(C++20)"

It is available on all major compilers such as GCC, Clang and MSVC.

**Comment by orignal** [comment]
vain is not supported.
Please don't create any tickets about it or it will be removed completely.

**Comment by orignal** [comment]
FYI, boost::filesystem is used by the main i2pd for C++11 support. 
No reason to rewrite it to std::filesystem  just for C++17 especially it's not supported by any C++17, g++-7 for example.
